<?php

namespace ContainerMUOyZVI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFarmerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.EjDLQHH.App\Entity\Farmer' shared service.
     *
     * @return \App\Entity\Farmer
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.EjDLQHH": it references class "App\\Entity\\Farmer" but no such service exists.');
    }
}
