<?php

namespace ContainerMUOyZVI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFilterDepartmentsTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\FilterDepartmentsType' shared autowired service.
     *
     * @return \App\Form\FilterDepartmentsType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/FilterDepartmentsType.php';

        return $container->privates['App\\Form\\FilterDepartmentsType'] = new \App\Form\FilterDepartmentsType(($container->privates['App\\Repository\\CityRepository'] ?? $container->load('getCityRepositoryService')));
    }
}
